# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dwg.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'dwg.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tdwg.proto\x12\x04\x66ile\"(\n\tFileChunk\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\r\n\x05index\x18\x02 \x01(\x05\"a\n\x0eUploadResponse\x12+\n\x06status\x18\x01 \x01(\x0e\x32\x1b.file.UploadResponse.Status\"\"\n\x06Status\x12\x0b\n\x07SUCCESS\x10\x00\x12\x0b\n\x07\x46\x41ILURE\x10\x01\x32@\n\x0b\x46ileService\x12\x31\n\x06Upload\x12\x0f.file.FileChunk\x1a\x14.file.UploadResponse(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dwg_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FILECHUNK']._serialized_start=19
  _globals['_FILECHUNK']._serialized_end=59
  _globals['_UPLOADRESPONSE']._serialized_start=61
  _globals['_UPLOADRESPONSE']._serialized_end=158
  _globals['_UPLOADRESPONSE_STATUS']._serialized_start=124
  _globals['_UPLOADRESPONSE_STATUS']._serialized_end=158
  _globals['_FILESERVICE']._serialized_start=160
  _globals['_FILESERVICE']._serialized_end=224
# @@protoc_insertion_point(module_scope)
